# Generated by Django 2.2.17 on 2020-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsUpdates_EN', models.CharField(max_length=500)),
                ('newsUpdates_DE', models.CharField(max_length=500)),
            ],
        ),
    ]
