# Generated by Django 2.2.17 on 2021-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('events_EN', models.CharField(max_length=50)),
                ('events_DE', models.CharField(max_length=50)),
            ],
        ),
    ]
