# Generated by Django 2.2.17 on 2021-02-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_eventscalender'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, upload_to='pageOne/')),
                ('img_description_EN', models.CharField(max_length=100)),
                ('img_description_DE', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='eventscalender',
            name='events_DE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventscalender',
            name='events_EN',
            field=models.CharField(max_length=100),
        ),
    ]
