# Generated by Django 2.2.17 on 2021-02-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210206_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recentEvents',
            new_name='recentEvent',
        ),
    ]
