# Generated by Django 2.2.17 on 2021-02-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210206_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentevent',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
