# Generated by Django 2.2.17 on 2021-02-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210206_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyText_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyText_EN', models.TextField()),
                ('historyText_DE', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recentEvent_Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, upload_to='pageOne/')),
                ('img_description_EN', models.CharField(max_length=100)),
                ('img_description_DE', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='eventsCalender',
            new_name='eventsCalender_Home',
        ),
        migrations.RenameModel(
            old_name='newsUpdate',
            new_name='newsUpdate_Home',
        ),
        migrations.DeleteModel(
            name='recentEvent',
        ),
    ]
