# Generated by Django 2.2.17 on 2021-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210212_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='chairmenICJ_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timePeriod', models.CharField(max_length=50)),
                ('chairmen_EN', models.CharField(max_length=100)),
                ('viceChairmen_EN', models.CharField(max_length=100)),
                ('chairmen_DE', models.CharField(max_length=100)),
                ('viceChairmen_DE', models.CharField(max_length=100)),
            ],
        ),
    ]
